export const booksData = [
    {
      id: 1,
      name: 'To Kill a Mockingbird',
      edition: '1st Edition',
      year: 1960,
      author: 'Harper Lee',
      publisher: 'J.B. Lippincott & Co.',
      ISBN: '9780060935467',
      thumbnail:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg/800px-To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg",
      likes: 124,
      dislikes: 5,
      rating: 4.8,
      reviews: [
        { summary: 'Timeless classic', description: 'A profound impact on society and literature.', date: '2024-08-01' },
        { summary: 'Powerful', description: 'Incredible story and characters.', date: '2024-08-02' },
      ],
    },
    {
      id: 2,
      name: '1984',
      edition: '1st Edition',
      year: 1949,
      author: 'George Orwell',
      publisher: 'Secker & Warburg',
      ISBN: '9780451524935',
      thumbnail: 'https://upload.wikimedia.org/wikipedia/en/5/51/1984_first_edition_cover.jpg',
      likes: 200,
      dislikes: 15,
      rating: 4.6,
      reviews: [
        { summary: 'Disturbingly relevant', description: 'A chilling depiction of a dystopian future.', date: '2024-08-03' },
        { summary: 'Masterpiece', description: 'Orwell at his best.', date: '2024-08-04' },
      ],
    },
    {
      id: 3,
      name: 'Pride and Prejudice',
      edition: '1st Edition',
      year: 1813,
      author: 'Jane Austen',
      publisher: 'T. Egerton, Whitehall',
      ISBN: '9780141040349',
      thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/PrideAndPrejudiceTitlePage.jpg/800px-PrideAndPrejudiceTitlePage.jpg',
      likes: 150,
      dislikes: 3,
      rating: 4.7,
      reviews: [
        { summary: 'Elegant and witty', description: 'A delightful read with sharp social commentary.', date: '2024-08-05' },
        { summary: 'Loved it', description: 'A timeless romance.', date: '2024-08-06' },
      ],
    },
    {
      id: 4,
      name: 'The Great Gatsby',
      edition: '1st Edition',
      year: 1925,
      author: 'F. Scott Fitzgerald',
      publisher: 'Charles Scribner\'s Sons',
      ISBN: '9780743273565',
      thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/The_Great_Gatsby_Cover_1925_Retouched.jpg/800px-The_Great_Gatsby_Cover_1925_Retouched.jpg',
      likes: 178,
      dislikes: 8,
      rating: 4.4,
      reviews: [
        { summary: 'Haunting', description: 'A tragic love story set against the Jazz Age.', date: '2024-08-07' },
        { summary: 'Brilliant', description: 'Fitzgerald\'s prose is unmatched.', date: '2024-08-08' },
      ],
    },
    {
      id: 5,
      name: 'Moby-Dick',
      edition: '1st Edition',
      year: 1851,
      author: 'Herman Melville',
      publisher: 'Harper & Brothers',
      ISBN: '9780142437247',
      thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Moby-Dick_FE_title_page.jpg/330px-Moby-Dick_FE_title_page.jpg',
      likes: 112,
      dislikes: 25,
      rating: 4.2,
      reviews: [
        { summary: 'Epic and profound', description: 'A deep exploration of obsession and revenge.', date: '2024-08-09' },
        { summary: 'Complex', description: 'A challenging but rewarding read.', date: '2024-08-10' },
      ],
    },
    {
      id: 6,
      name: 'War and Peace',
      edition: '1st Edition',
      year: 1869,
      author: 'Leo Tolstoy',
      publisher: 'The Russian Messenger',
      ISBN: '9780199232765',
      thumbnail: 'https://m.media-amazon.com/images/I/81oHM-dzefL._SL1500_.jpg',
      likes: 134,
      dislikes: 10,
      rating: 4.5,
      reviews: [
        { summary: 'Epic in scope', description: 'A masterpiece of historical fiction.', date: '2024-08-11' },
        { summary: 'Long but worth it', description: 'A deep dive into Russian history and human nature.', date: '2024-08-12' },
      ],
    },
    {
      id: 7,
      name: 'The Catcher in the Rye',
      edition: '1st Edition',
      year: 1951,
      author: 'J.D. Salinger',
      publisher: 'Little, Brown and Company',
      ISBN: '9780316769488',
      thumbnail: 'https://m.media-amazon.com/images/I/618XWn5fD5L._SL1360_.jpg',
      likes: 159,
      dislikes: 12,
      rating: 4.3,
      reviews: [
        { summary: 'Iconic', description: 'A unique voice in literature, capturing adolescent angst.', date: '2024-08-13' },
        { summary: 'Relatable', description: 'Holden Caulfield is unforgettable.', date: '2024-08-14' },
      ],
    },
    {
      id: 8,
      name: 'Brave New World',
      edition: '1st Edition',
      year: 1932,
      author: 'Aldous Huxley',
      publisher: 'Chatto & Windus',
      ISBN: '9780060850524',
      thumbnail: 'https://m.media-amazon.com/images/I/51CWnp7rtlL.jpg',
      likes: 141,
      dislikes: 18,
      rating: 4.4,
      reviews: [
        { summary: 'Thought-provoking', description: 'A bleak vision of a controlled society.', date: '2024-08-15' },
        { summary: 'Huxley\'s best', description: 'Still relevant in today\'s world.', date: '2024-08-16' },
      ],
    },
    {
      id: 9,
      name: 'Jane Eyre',
      edition: '1st Edition',
      year: 1847,
      author: 'Charlotte Brontë',
      publisher: 'Smith, Elder & Co.',
      ISBN: '9780141441146',
      thumbnail: 'https://m.media-amazon.com/images/I/81pwJjgcwwL._SL1500_.jpg',
      likes: 169,
      dislikes: 6,
      rating: 4.6,
      reviews: [
        { summary: 'Captivating', description: 'A strong female protagonist ahead of her time.', date: '2024-08-17' },
        { summary: 'Romantic and Gothic', description: 'A perfect blend of romance and mystery.', date: '2024-08-18' },
      ],
    },
    {
      id: 10,
      name: 'The Hobbit',
      edition: '1st Edition',
      year: 1937,
      author: 'J.R.R. Tolkien',
      publisher: 'George Allen & Unwin',
      ISBN: '9780547928227',
      thumbnail: 'https://m.media-amazon.com/images/I/71jKeGU9nKL._SL1161_.jpg',
      likes: 190,
      dislikes: 4,
      rating: 4.9,
      reviews: [
        { summary: 'A true classic', description: 'An adventure that has stood the test of time.', date: '2024-08-19' },
        { summary: 'Fantastic world-building', description: 'Tolkien\'s world is rich and immersive.', date: '2024-08-20' },
      ],
    },
  ];
  